spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: gims
  datasource:
    url: jdbc:h2:file:./data/testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      format_sql: true
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secret: AOArdi/JR0KSSq7md4ZbAXEb0qHK2CEhdx74gMY2MgI=
  expiration-ms: 86400000  # 24h

server:
  tomcat:
    max-http-form-post-size: 10MB
  compression:
    enabled: true
    min-response-size: 1024
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        secure: false
        http-only: false
        same-site: None
      timeout: 600m
  port: ${SERVER_PORT}